// kiro-generated
/**
 * Spellbook Template System
 * 
 * Pure functions that generate MCP server files from Spell definitions.
 * Each template produces a complete file ready for deployment.
 */

import type { Spell, Action, AuthSchema } from './types.js';
import type { z } from 'zod'; // We need z.infer
type AuthConfig = z.infer<typeof AuthSchema>;

// ============================================================================
// Template Functions
// ============================================================================

/**
 * Templates object containing all file generation functions.
 * Each function is pure: same input -> same output, no side effects.
 */
export const templates = {
  dockerfile,
  packageJson,
  serverCode,
  readme,
  oauthSetup
};

// ============================================================================
// Dockerfile Template
// ============================================================================

/**
 * Generates a production-ready Dockerfile for containerizing the MCP server.
 * Features: multi-stage build, non-root user, health check, security hardening.
 */
function dockerfile(spell: Spell): string {
  const hasIsolatedScript = spell.tools.some(t => t.action.type === 'script' && t.action.config.execution === 'isolated');
  const hasSse = spell.transport === 'sse';

  return `# Production Dockerfile for ${spell.name}
# Generated by Spellbook

# Build stage
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies first (better layer caching)
COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi

# Copy source
COPY . .

# Production stage
FROM node:20-alpine

# Security: Create non-root user
RUN addgroup -g 1001 -S nodejs && \\
    adduser -S nodejs -u 1001

WORKDIR /app

# Copy from builder
COPY --from=builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nodejs:nodejs /app/*.js ./
COPY --from=builder --chown=nodejs:nodejs /app/package.json ./

# Security: Run as non-root
USER nodejs

# Expose port for SSE transport
${hasSse ? 'EXPOSE 3000' : ''}

# Environment defaults
ENV NODE_ENV=production
ENV PORT=3000
ENV LOG_LEVEL=info
${hasIsolatedScript ? 'ENV SANDBOX_MEMORY_MB=32' : ''}

# Health check (for SSE transport)
${hasSse ? 'HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\\\\n  CMD wget -qO- http://localhost:3000/health || exit 1' : ''}

# Start server
CMD ["node", "index.js"]
`;
}


// ============================================================================
// package.json Template
// ============================================================================

/**
 * Generates package.json with dependencies and metadata.
 * Configures ES modules and includes MCP SDK.
 */
function packageJson(spell: Spell): string {
  const hasIsolatedScript = spell.tools.some(t => t.action.type === 'script' && t.action.config.execution === 'isolated');

  const pkg = {
    name: `spell-${spell.name}`,
    version: '1.0.0',
    type: 'module',
    main: 'index.js',
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0',
      'ajv': '^8.12.0',
      'zod': '^3.22.4',
      ...(hasIsolatedScript ? { 'isolated-vm': '^4.6.0' } : {}),
      ...(spell.transport === 'sse' || spell.auth?.type === 'oauth2' ? {
        'express': '^4.18.2'
      } : {}),
      ...(spell.auth?.type === 'oauth2' ? {
        'axios': '^1.6.0',
        'dotenv': '^16.3.1',
        'open': '^9.1.0'
      } : {})
    }
  };

  return formatJson(pkg);
}

// ============================================================================
// Server Code Template
// ============================================================================

/**
 * Generates the MCP server implementation.
 * Handles tool registration, request processing, and action execution.
 */
/**
 * Generates the MCP server implementation.
 * Handles tool registration, request processing, and action execution.
 */
function serverCode(spell: Spell): string {
  const needsInterpolation = checkNeedsInterpolation(spell);
  const needsHttpHelpers = spell.tools.some(t => t.action.type === 'http');
  const hasIsolatedScript = spell.tools.some(t => t.action.type === 'script' && t.action.config.execution === 'isolated');

  return `import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { SSEServerTransport } from '@modelcontextprotocol/sdk/server/sse.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema
} from '@modelcontextprotocol/sdk/types.js';
import Ajv from 'ajv';
import { z } from 'zod';
${hasIsolatedScript ? `import ivm from 'isolated-vm';` : ''}
${spell.transport === 'sse' ? `import express from 'express';` : ''}

// JSON Schema validation using Ajv
const ajv = new Ajv({ allErrors: true, coerceTypes: true });

// Security: Configurable via environment variables
const ALLOWED_HOSTS = process.env.ALLOWED_HOSTS ? process.env.ALLOWED_HOSTS.split(',').map(h => h.trim()) : ['*'];
const MAX_RESPONSE_SIZE = parseInt(process.env.MAX_RESPONSE_SIZE) || 10 * 1024 * 1024; // 10MB default

// Authentication check
${spell.auth ? (
      spell.auth.type === 'oauth2'
        ? `const AUTH_ENV_VAR = '${spell.auth.config.tokenEnvVar}';
if (!process.env[AUTH_ENV_VAR]) {
  console.error(\` Missing required environment variable: \${AUTH_ENV_VAR}\`);
  console.error(\` Run "node setup-auth.js" to authenticate first.\`);
  throw new Error(\`Server requires environment variable \${AUTH_ENV_VAR} to be set for authentication.\`);
}`
        : `const AUTH_ENV_VAR = '${spell.auth.envVar}';
if (!process.env[AUTH_ENV_VAR]) {
  console.error(\` Missing required environment variable: \${AUTH_ENV_VAR}\`);
  throw new Error(\`Server requires environment variable \${AUTH_ENV_VAR} to be set for authentication.\`);
}`
    ) : ''}

${needsInterpolation ? generateInterpolateFunction() + '\n' : ''}
${needsHttpHelpers ? generateReadBodyWithLimitFunction() + '\n' : ''}

// Tool Definitions & Handlers
const tools = {
${spell.tools.map(tool => {
      const hasOutputSchema = tool.outputSchema && Object.keys(tool.outputSchema.properties || {}).length > 0;
      return `  '${escapeString(tool.name)}': {
    definition: {
      name: '${escapeString(tool.name)}',
      description: '${escapeString(tool.description)}',
      inputSchema: ${formatJson(tool.inputSchema)}
    },
    validateInput: ajv.compile(${formatJson(tool.inputSchema)}),
    validateOutput: ajv.compile(${formatJson(tool.outputSchema)}),
    action: async (input, authToken) => {
${generateActionCode(tool.action, spell.auth)}
    },
    hasOutputSchema: ${hasOutputSchema}
  }`;
    }).join(',\n')}
};

// Runtime Integrity Check
Object.values(tools).forEach(tool => {
  try {
    const ToolDefinitionSchema = z.object({
      name: z.string(),
      description: z.string(),
      inputSchema: z.record(z.any()),
    });
    ToolDefinitionSchema.parse(tool.definition);
  } catch(e) {
    console.error(\` Tool integrity check failed for \${tool.definition.name}:\`, e);
    process.exit(1);
  }
});

// Server setup
const server = new Server({
  name: '${escapeString(spell.name)}',
  version: '1.0.0'
}, {
  capabilities: { tools: {} }
});

// List tools handler
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: Object.values(tools).map(t => t.definition)
}));

// Call tool handler
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const toolName = request.params.name;
  const tool = tools[toolName];

  if (!tool) {
    throw new Error(\`Unknown tool: \${toolName}\`);
  }
  
  try {
    const input = request.params.arguments || {};
    
    // Validate input against JSON Schema using Ajv
    if (!tool.validateInput(input)) {
      const errors = tool.validateInput.errors?.map(e => \`\${e.instancePath} \${e.message}\`).join(', ');
      throw new Error(\`Invalid input: \${errors}\`);
    }
    
    // Get auth token if configured
    const authToken = ${spell.auth
      ? (spell.auth.type === 'oauth2'
        ? `process.env['${spell.auth.config.tokenEnvVar}']`
        : `process.env['${spell.auth.envVar}']`)
      : 'undefined'
    };
    const result = await tool.action(input, authToken);
    
    // Validate output against JSON Schema (enforced)
    if (tool.hasOutputSchema && !tool.validateOutput(result)) {
      const errors = tool.validateOutput.errors?.map(e => \`\${e.instancePath} \${e.message}\`).join(', ');
      throw new Error(\`Output validation failed: \${errors}\`);
    }
    
    return {
      content: [{
        type: "text",
        text: JSON.stringify(result, null, 2)
      }]
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    const errorStack = error instanceof Error ? error.stack : undefined;
    return {
      content: [{
        type: "text",
        text: JSON.stringify({ 
          error: errorMessage,
          details: errorStack ? errorStack.split('\\n').slice(0, 3).join('\\n') : undefined
        }, null, 2)
      }],
      isError: true
    };
  }
});

// Transport setup
// Transport setup
${spell.transport === 'sse' ? `
const app = express();
app.use(express.json());

// Health check state
const serverStartTime = Date.now();

// Health endpoint - for liveness probes
app.get('/health', (req, res) => {
  const memUsage = process.memoryUsage();
  const maxMemory = parseInt(process.env.MAX_MEMORY_MB) || 256;
  const memoryOk = memUsage.heapUsed < maxMemory * 1024 * 1024;
  
  const health = {
    status: memoryOk ? 'healthy' : 'degraded',
    checks: {
      memory: {
        status: memoryOk ? 'pass' : 'fail',
        used_mb: Math.round(memUsage.heapUsed / 1024 / 1024),
        limit_mb: maxMemory
      },
      uptime: {
        status: 'pass',
        seconds: Math.round((Date.now() - serverStartTime) / 1000)
      }
    },
    timestamp: new Date().toISOString()
  };
  
  res.status(health.status === 'healthy' ? 200 : 503).json(health);
});

// Ready endpoint - for readiness probes
app.get('/ready', (req, res) => {
  res.json({ ready: true, timestamp: new Date().toISOString() });
});

const transports = {};

app.get('/sse', async (req, res) => {
  const transport = new SSEServerTransport('/messages', res);
  transports[transport.sessionId] = transport;

  res.on('close', () => {
    delete transports[transport.sessionId];
  });

  await server.connect(transport);
});

app.post('/messages', async (req, res) => {
  const sessionId = req.query.sessionId;
  const transport = sessionId ? transports[sessionId] : undefined;

  if (!transport) {
    res.status(400).send('No transport found for sessionId');
    return;
  }

  await transport.handlePostMessage(req, res, req.body);
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(JSON.stringify({ level: 'info', event: 'server_started', port: PORT, transport: 'sse' }));
  console.log(\` Spellbook Server running on SSE transport at port \${PORT}\`);
  console.log(\` Health: http://localhost:\${PORT}/health\`);
  console.log(\` SSE: http://localhost:\${PORT}/sse\`);
});
` : `
const transport = new StdioServerTransport();
await server.connect(transport);
`}
`;
}

// ============================================================================
// README Template
// ============================================================================

/**
 * Generates documentation for the MCP tool.
 * Includes installation, usage, and schema information.
 */
/**
 * Generates documentation for the MCP tool.
 * Includes installation, usage, and schema information.
 */
function readme(spell: Spell): string {
  const toolsDoc = spell.tools.map(tool => {
    const isScript = tool.action.type === 'script';
    const securityNote = isScript
      ? `>  **Security Notice**: This tool executes JavaScript code with full Node.js privileges.`
      : `>  **Network**: Makes HTTP requests. Checked against \`ALLOWED_HOSTS\`.`;

    return `### ${tool.name}
${tool.description}

${securityNote}

#### Input Schema
\`\`\`json
${formatJson(tool.inputSchema)}
\`\`\`

#### Output Schema
\`\`\`json
${formatJson(tool.outputSchema)}
\`\`\`
`;
  }).join('\n---\n\n');

  return `# ${spell.name}

${spell.description}

## Installation

\`\`\`bash
docker build -t ${spell.name} .
\`\`\`

## Usage in Kiro

Add to \`.kiro/settings/mcp.json\`:

\`\`\`json
{
  "mcpServers": {
    "${spell.name}": {
      "command": "docker",
      "args": ["run", "--rm", "-i", "${spell.name}"]
    }
  }
}
\`\`\`

## Available Tools

${toolsDoc}

## Configuration

Configure via environment variables:

| Variable | Default | Description |
|----------|---------|-------------|
| \`ALLOWED_HOSTS\` | \`*\` (all) | Comma-separated list of allowed domains |
| \`MAX_RESPONSE_SIZE\` | \`10485760\` | Max response size in bytes (10MB) |
| \`HTTP_TIMEOUT_MS\` | \`15000\` | HTTP request timeout in milliseconds |
| \`SCRIPT_TIMEOUT_MS\` | \`5000\` | Script execution timeout in milliseconds |

Example:
\`\`\`bash
ALLOWED_HOSTS=api.github.com,api.example.com docker run --rm -i ${spell.name}
\`\`\`
`;
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Generates action-specific execution code.
 * Handles HTTP requests and script execution.
 */
function generateActionCode(action: Action, auth?: AuthConfig): string {
  if (action.type === 'http') {
    const { url, method, headers, body } = action.config;

    // Build fetch options
    const fetchOptions: string[] = [`method: '${method}'`];

    // Construct headers object
    const headerEntries: string[] = [];

    // Add auth header if configured
    if (auth) {
      const headerKey = auth.type === 'apiKey' && auth.headerKey
        ? auth.headerKey
        : (auth.type === 'bearer' || auth.type === 'oauth2' ? 'Authorization' : 'x-api-key');

      const headerValue = auth.type === 'bearer' || auth.type === 'oauth2' ? `Bearer \${authToken}` : `\${authToken}`;
      headerEntries.push(`'${headerKey}': \`${headerValue}\``);
    }

    // Support {{variable}} interpolation in headers
    if (headers && Object.keys(headers).length > 0) {
      Object.entries(headers).forEach(([k, v]) => {
        if (v.includes('{{')) {
          headerEntries.push(`'${escapeString(k)}': interpolate(${JSON.stringify(v)}, input)`);
        } else {
          headerEntries.push(`'${escapeString(k)}': ${JSON.stringify(v)}`);
        }
      });
    }

    if (headerEntries.length > 0) {
      fetchOptions.push(`headers: {\n      ${headerEntries.join(',\n      ')}\n}`);
    }

    if (body) {
      const bodyCode = body.includes('{{')
        ? `body: interpolate(${JSON.stringify(body)}, input)`
        : `body: ${JSON.stringify(body)}`;
      fetchOptions.push(bodyCode);
    }


    const urlCode = url.includes('{{')
      ? `interpolate('${escapeString(url)}', input, { encode: true })`
      : `'${escapeString(url)}'`;

    return `  const timeoutMs = parseInt(process.env.HTTP_TIMEOUT_MS) || 15000;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const targetUrl = ${urlCode};
    
    // Security: Validate URL protocol and host
    const parsedUrl = new URL(targetUrl);
    const allowedProtocols = ['http:', 'https:'];
    if (!allowedProtocols.includes(parsedUrl.protocol)) {
      throw new Error(\`Protocol not allowed: \${parsedUrl.protocol}. Use http: or https:\`);
    }
    if (!ALLOWED_HOSTS.includes('*') && !ALLOWED_HOSTS.includes(parsedUrl.host)) {
      throw new Error(\`Host not allowed: \${parsedUrl.host}. Allowed: \${ALLOWED_HOSTS.join(', ')}\`);
    }
    
    const response = await fetch(targetUrl, {
      signal: controller.signal,
      ${fetchOptions.join(',\n      ')}
    });
    
    // Check response size before reading
    const contentLength = response.headers.get('content-length');
    if (contentLength && parseInt(contentLength) > MAX_RESPONSE_SIZE) {
      throw new Error(\`Response too large: \${contentLength} bytes (max: \${MAX_RESPONSE_SIZE})\`);
    }
    
    if (!response.ok) {
      const errorBody = await response.text().catch(() => 'Unable to read error body');
      throw new Error(\`HTTP \${response.status} \${response.statusText}: \${errorBody.slice(0, 500)}\`);
    }
    
    const text = await readBodyWithLimit(response, MAX_RESPONSE_SIZE);
    
    try {
      return JSON.parse(text);
    } catch {
      return { data: text };
    }
  } catch (err) {
    if (err && err.name === 'AbortError') {
      throw new Error(\`Request timed out after \${timeoutMs}ms\`);
    }
    throw err;
  } finally {
    clearTimeout(timeout);
  }`;
  } else {
    // Script action
    const { code, execution } = action.config;

    if (execution === 'isolated') {
      return `  //  SANDBOXED EXECUTION (isolated-vm)
  // Memory limit configurable via SANDBOX_MEMORY_MB (default: 32MB)
  const memoryLimit = parseInt(process.env.SANDBOX_MEMORY_MB) || 32;
  const isolate = new ivm.Isolate({ memoryLimit });
  const context = isolate.createContextSync();
  const jail = context.global;

  // Make 'input' available to the script
  jail.setSync('global', jail.derefInto());
  jail.setSync('input', new ivm.ExternalCopy(input).copyInto());
  
  // Compile the user script
  const script = isolate.compileScriptSync(${JSON.stringify(code)});
  const timeoutMs = parseInt(process.env.SCRIPT_TIMEOUT_MS) || 5000;
  
  try {
    const result = await script.run(context, { timeout: timeoutMs, copy: true });
    return result;
  } catch (err) {
    throw new Error(\`Sandbox execution failed: \${err.message}\`);
  }`;
    } else {
      // Unsafe execution
      return `  // WARNING: Script runs with full Node.js privileges. Only run trusted code.
  const fn = new Function('input', ${JSON.stringify(code)});
  const timeoutMs = parseInt(process.env.SCRIPT_TIMEOUT_MS) || 5000;
  let timeout;

  try {
    const execution = Promise.resolve().then(() => fn(input));
    const timeoutPromise = new Promise((_, reject) => {
      timeout = setTimeout(() => reject(new Error(\`Script timed out after \${timeoutMs}ms\`)), timeoutMs);
    });
    const result = await Promise.race([execution, timeoutPromise]);
    
    // Ensure result is serializable
    if (result === undefined) {
      return { success: true };
    }
    JSON.stringify(result); // Throws if not serializable
    return result;
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new Error(\`Script syntax error: \${err.message}\`);
    }
    throw err;
  } finally {
    if (timeout) clearTimeout(timeout);
  }`;
    }
  }
}

/**
 * Escapes strings for safe embedding in generated code.
 * Prevents code injection vulnerabilities.
 * 
 * Strategy:
 * 1. Use JSON.stringify to handle robust escaping of backslashes, newlines, control chars, etc.
 * 2. Remove surrouding double quotes.
 * 3. Escape single quotes (since we embed in '...').
 * 4. Escape backticks and ${ to prevent template interpolation if used in `...` context.
 */
function escapeString(str: string): string {
  if (!str) return '';
  return JSON.stringify(str)
    .slice(1, -1)
    .replace(/'/g, "\\'")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

/**
 * Formats JSON with proper indentation.
 * Used for embedding schemas in generated code.
 * Returns empty object if undefined/null to prevent invalid JS.
 */
function formatJson(obj: any): string {
  if (obj === undefined || obj === null) {
    return '{}';
  }
  return JSON.stringify(obj, null, 2);
}

/**
 * Generates interpolation helper function for server code.
 * Supports nested paths like {{user.profile.name}} and provides
 * warnings for undefined variables instead of silent failures.
 */
function generateInterpolateFunction(): string {
  return `/**
 * Interpolates {{path}} placeholders with values from vars.
 * Supports nested paths: {{user.name}}, {{config.api.key}}
 * @param template - String containing {{path}} placeholders
 * @param vars - Object containing values to interpolate
 * @param options - { encode: boolean } - URL-encode values (default: false)
 */
function interpolate(template, vars, options = {}) {
  const { encode = false } = options;
  return template.replace(/\\{\\{([\\w.]+)\\}\\}/g, (match, path) => {
    // Resolve nested path: "user.profile.name" -> vars.user.profile.name
    const value = path.split('.').reduce((obj, key) => {
      if (obj === undefined || obj === null) return undefined;
      return obj[key];
    }, vars);
    
    if (value === undefined) {
      console.warn(\`[Spellbook] Interpolation warning: "\${path}" is undefined in input\`);
      return '';
    }
    
    const strValue = String(value);
    return encode ? encodeURIComponent(strValue) : strValue;
  });
}`;
}


/**
 * Checks if a spell needs the interpolation helper function.
 * Returns true if URL, body, or headers contain {{variable}} syntax.
 */
function checkNeedsInterpolation(spell: Spell): boolean {
  for (const tool of spell.tools) {
    if (tool.action.type !== 'http') continue;

    const { url, body, headers } = tool.action.config;

    if (url.includes('{{')) return true;
    if (body && body.includes('{{')) return true;
    if (headers && Object.values(headers).some(v => v.includes('{{'))) return true;
  }
  return false;
}

/**
 * Generates a helper to stream responses with a hard size cap.
 */
function generateReadBodyWithLimitFunction(): string {
  return `async function readBodyWithLimit(response, maxBytes) {
  const reader = response.body?.getReader();
  if (!reader) {
    const text = await response.text();
    if (text.length > maxBytes) {
      throw new Error(\`Response too large: \${text.length} bytes (max: \${maxBytes})\`);
    }
    return text;
  }
  
  const decoder = new TextDecoder();
  let chunks = [];
  let total = 0;
  
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    total += value.byteLength;
    if (total > maxBytes) {
      reader.cancel();
      throw new Error(\`Response too large: exceeded \${maxBytes} bytes\`);
    }
    chunks.push(decoder.decode(value, { stream: true }));
  }
  
  return chunks.join('');
}`;
}

// ============================================================================
// OAuth Setup Sidecar
// ============================================================================

/**
 * Generates the Sidecar script for handling OAuth 2.1 flow.
 * Spins up a temp server to catch the callback and exchange code for token.
 */
function oauthSetup(spell: Spell): string | null {
  if (spell.auth?.type !== 'oauth2') return null;
  const config = spell.auth.config;

  return `
/**
 *  OAuth 2.1 Sidecar
 * Run this script to authenticate your spell with ${escapeString(config.authUrl)}
 * 
 * Features:
 * - Automatic port fallback (tries 3456-3460)
 * - 5-minute timeout for the entire flow
 * - Structured error messages
 */
import 'dotenv/config';
import express from 'express';
import axios from 'axios';
import open from 'open';
import fs from 'fs';
import path from 'path';
import net from 'net';

// Config
const CLIENT_ID = '${escapeString(config.clientId)}';
const CLIENT_SECRET_ENV_VAR = '${escapeString(config.clientSecretEnvVar ?? 'CLIENT_SECRET')}';
const CLIENT_SECRET = process.env[CLIENT_SECRET_ENV_VAR];
const AUTH_URL = '${escapeString(config.authUrl)}';
const TOKEN_URL = '${escapeString(config.tokenUrl)}';
const SCOPES = '${escapeString(config.scopes.join(' '))}';
const PORTS_TO_TRY = [3456, 3457, 3458, 3459, 3460];
const FLOW_TIMEOUT_MS = 5 * 60 * 1000;
const ENV_FILE = path.join(process.cwd(), '.env');

if (!CLIENT_SECRET) {
  console.error(JSON.stringify({ level: 'error', message: 'OAuth client secret not set', envVar: CLIENT_SECRET_ENV_VAR }));
  process.exit(1);
}

async function findAvailablePort(ports) {
  for (const port of ports) {
    const available = await new Promise((resolve) => {
      const server = net.createServer();
      server.once('error', () => resolve(false));
      server.once('listening', () => { server.close(); resolve(true); });
      server.listen(port);
    });
    if (available) return port;
  }
  throw new Error('No available ports in range ' + ports[0] + '-' + ports[ports.length - 1]);
}

async function main() {
  const PORT = await findAvailablePort(PORTS_TO_TRY);
  const REDIRECT_URI = 'http://localhost:' + PORT + '/callback';
  
  console.log(JSON.stringify({ level: 'info', message: 'Starting OAuth Sidecar', port: PORT }));
  
  const flowTimeout = setTimeout(() => {
    console.error(JSON.stringify({ level: 'error', message: 'OAuth flow timed out' }));
    process.exit(1);
  }, FLOW_TIMEOUT_MS);

  const app = express();

  app.get('/callback', async (req, res) => {
    clearTimeout(flowTimeout);
    const code = req.query.code;
    const error = req.query.error;
    
    if (error) {
      console.error(JSON.stringify({ level: 'error', message: 'OAuth error', error }));
      res.status(400).send('<h1>Authentication Failed</h1>');
      process.exit(1);
    }
    
    if (!code) {
      res.status(400).send('<h1>No authorization code</h1>');
      return;
    }

    try {
      console.log(JSON.stringify({ level: 'info', message: 'Exchanging code for token...' }));
      
      const tokenRes = await axios.post(TOKEN_URL, {
        client_id: CLIENT_ID,
        client_secret: CLIENT_SECRET,
        code,
        redirect_uri: REDIRECT_URI,
        grant_type: 'authorization_code'
      }, {
        headers: { 'Accept': 'application/json' },
        timeout: 10000
      });

      const { access_token, refresh_token, expires_in } = tokenRes.data;
      
      if (!access_token) {
        throw new Error('No access_token in response');
      }
      
      const envLines = [
        '${config.tokenEnvVar}=' + access_token,
        refresh_token ? 'MCP_REFRESH_TOKEN=' + refresh_token : null,
        expires_in ? 'MCP_TOKEN_EXPIRES_IN=' + expires_in : null
      ].filter(Boolean);

      fs.writeFileSync(ENV_FILE, envLines.join('\\n'));
      
      console.log(JSON.stringify({ level: 'info', message: 'Authentication successful!', tokenFile: ENV_FILE }));
      res.send('<h1>Authentication Successful!</h1><p>You can close this tab.</p>');
      setTimeout(() => process.exit(0), 1000);

    } catch (error) {
      console.error(JSON.stringify({ level: 'error', message: 'Token exchange failed', error: error.message }));
      res.status(500).send('<h1>Token Exchange Failed</h1>');
      process.exit(1);
    }
  });

  const server = app.listen(PORT, async () => {
    const loginUrl = AUTH_URL + '?client_id=' + CLIENT_ID + '&redirect_uri=' + encodeURIComponent(REDIRECT_URI) + '&response_type=code&scope=' + encodeURIComponent(SCOPES);
    console.log(JSON.stringify({ level: 'info', message: 'Opening browser...', url: loginUrl }));
    try { await open(loginUrl); } catch (err) {
      console.log(JSON.stringify({ level: 'warn', message: 'Could not open browser', hint: 'Open URL manually: ' + loginUrl }));
    }
  });
  
  server.on('error', (err) => {
    console.error(JSON.stringify({ level: 'error', message: 'Server error', error: err.message }));
    process.exit(1);
  });
}

main().catch((err) => {
  console.error(JSON.stringify({ level: 'error', message: 'Startup failed', error: err.message }));
  process.exit(1);
});
`;
}
