/**
 * Spellbook: Kubernetes Manifest Generator
 * 
 * Generates production-ready Kubernetes manifests for MCP servers.
 */

import type { Spell } from '../types.js';

export interface K8sManifestOptions {
    /** Docker image name */
    image: string;
    /** Number of replicas */
    replicas?: number;
    /** Namespace */
    namespace?: string;
    /** Resource requests */
    resources?: {
        requests?: { memory?: string; cpu?: string };
        limits?: { memory?: string; cpu?: string };
    };
}

/**
 * Generate Kubernetes manifests for a spell.
 */
export function generateK8sManifests(spell: Spell, options: K8sManifestOptions): string {
    const name = spell.name;
    const image = options.image;
    const replicas = options.replicas ?? 2;
    const namespace = options.namespace ?? 'default';
    const resources = options.resources ?? {
        requests: { memory: '128Mi', cpu: '100m' },
        limits: { memory: '256Mi', cpu: '500m' },
    };

    return `# Generated by Spellbook for ${name}
# Apply with: kubectl apply -f k8s.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}-config
  namespace: ${namespace}
data:
  config.json: |
    {
      "port": 3000,
      "logLevel": "info"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: ${name}-secrets
  namespace: ${namespace}
type: Opaque
stringData:
  # Add your secrets here
  API_KEY: "YOUR_API_KEY_HERE"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    app: ${name}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
      - name: server
        image: ${image}
        ports:
        - containerPort: 3000
        env:
        - name: CONFIG
          valueFrom:
            configMapKeyRef:
              name: ${name}-config
              key: config.json
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: ${name}-secrets
              key: API_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "${resources.requests?.memory ?? '128Mi'}"
            cpu: "${resources.requests?.cpu ?? '100m'}"
          limits:
            memory: "${resources.limits?.memory ?? '256Mi'}"
            cpu: "${resources.limits?.cpu ?? '500m'}"
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  selector:
    app: ${name}
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  minReplicas: ${replicas}
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
`;
}
