/**
 * Spellbook Runtime: Terraform Module Generator
 * 
 * Generates Terraform modules for deploying MCP servers
 * to AWS, GCP, or Azure.
 */

import type { Spell } from '../types.js';

// ============================================================================
// Types
// ============================================================================

export interface TerraformOptions {
    /** Cloud provider */
    provider: 'aws' | 'gcp' | 'azure';
    /** Docker image name */
    image: string;
    /** AWS region or GCP zone */
    region?: string;
    /** Min replicas */
    minReplicas?: number;
    /** Max replicas */
    maxReplicas?: number;
    /** CPU allocation (e.g., "256" for 0.25 vCPU) */
    cpu?: string;
    /** Memory allocation (e.g., "512" for 512 MB) */
    memory?: string;
    /** Environment variables */
    envVars?: Record<string, string>;
    /** Secret references */
    secrets?: string[];
}

// ============================================================================
// AWS ECS Module
// ============================================================================

function generateAWSModule(spell: Spell, options: TerraformOptions): string {
    const name = spell.name;
    const region = options.region ?? 'us-east-1';
    const minReplicas = options.minReplicas ?? 2;
    const maxReplicas = options.maxReplicas ?? 10;
    const cpu = options.cpu ?? '256';
    const memory = options.memory ?? '512';

    return `# Terraform module for ${name}
# Generated by Spellbook

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "${region}"
}

# Variables
variable "image" {
  description = "Docker image for the MCP server"
  type        = string
  default     = "${options.image}"
}

variable "environment" {
  description = "Environment (dev, staging, prod)"
  type        = string
  default     = "prod"
}

# VPC (use existing or create)
data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

# ECS Cluster
resource "aws_ecs_cluster" "${name}_cluster" {
  name = "${name}-\${var.environment}"
  
  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

# ECS Task Definition
resource "aws_ecs_task_definition" "${name}_task" {
  family                   = "${name}"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "${cpu}"
  memory                   = "${memory}"
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  
  container_definitions = jsonencode([{
    name  = "${name}"
    image = var.image
    
    portMappings = [{
      containerPort = 3000
      hostPort      = 3000
      protocol      = "tcp"
    }]
    
    environment = [
      { name = "PORT", value = "3000" },
      { name = "LOG_LEVEL", value = "info" },
      { name = "NODE_ENV", value = var.environment }
    ]
    
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = "/ecs/${name}"
        "awslogs-region"        = "${region}"
        "awslogs-stream-prefix" = "ecs"
      }
    }
    
    healthCheck = {
      command     = ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval    = 30
      timeout     = 5
      retries     = 3
      startPeriod = 60
    }
  }])
}

# ECS Service
resource "aws_ecs_service" "${name}_service" {
  name            = "${name}"
  cluster         = aws_ecs_cluster.${name}_cluster.id
  task_definition = aws_ecs_task_definition.${name}_task.arn
  desired_count   = ${minReplicas}
  launch_type     = "FARGATE"
  
  network_configuration {
    subnets         = data.aws_subnets.default.ids
    security_groups = [aws_security_group.${name}_sg.id]
    assign_public_ip = true
  }
  
  load_balancer {
    target_group_arn = aws_lb_target_group.${name}_tg.arn
    container_name   = "${name}"
    container_port   = 3000
  }
}

# Auto Scaling
resource "aws_appautoscaling_target" "${name}_scaling_target" {
  max_capacity       = ${maxReplicas}
  min_capacity       = ${minReplicas}
  resource_id        = "service/\${aws_ecs_cluster.${name}_cluster.name}/\${aws_ecs_service.${name}_service.name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_policy" "${name}_cpu_policy" {
  name               = "${name}-cpu-scaling"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.${name}_scaling_target.resource_id
  scalable_dimension = aws_appautoscaling_target.${name}_scaling_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.${name}_scaling_target.service_namespace
  
  target_tracking_scaling_policy_configuration {
    target_value = 70.0
    
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
  }
}

# Security Group
resource "aws_security_group" "${name}_sg" {
  name        = "${name}-sg"
  description = "Security group for ${name} MCP server"
  vpc_id      = data.aws_vpc.default.id
  
  ingress {
    from_port   = 3000
    to_port     = 3000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# ALB
resource "aws_lb" "${name}_alb" {
  name               = "${name}-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.${name}_sg.id]
  subnets            = data.aws_subnets.default.ids
}

resource "aws_lb_target_group" "${name}_tg" {
  name        = "${name}-tg"
  port        = 3000
  protocol    = "HTTP"
  vpc_id      = data.aws_vpc.default.id
  target_type = "ip"
  
  health_check {
    path                = "/health"
    healthy_threshold   = 2
    unhealthy_threshold = 10
  }
}

resource "aws_lb_listener" "${name}_listener" {
  load_balancer_arn = aws_lb.${name}_alb.arn
  port              = 80
  protocol          = "HTTP"
  
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.${name}_tg.arn
  }
}

# IAM
resource "aws_iam_role" "ecs_execution" {
  name = "${name}-ecs-execution"
  
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_execution" {
  role       = aws_iam_role.ecs_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

# CloudWatch Logs
resource "aws_cloudwatch_log_group" "${name}_logs" {
  name              = "/ecs/${name}"
  retention_in_days = 30
}

# Outputs
output "alb_dns" {
  value       = aws_lb.${name}_alb.dns_name
  description = "ALB DNS name for the MCP server"
}

output "cluster_name" {
  value = aws_ecs_cluster.${name}_cluster.name
}
`;
}

// ============================================================================
// GCP Cloud Run Module
// ============================================================================

function generateGCPModule(spell: Spell, options: TerraformOptions): string {
    const name = spell.name;
    const region = options.region ?? 'us-central1';
    const minReplicas = options.minReplicas ?? 1;
    const maxReplicas = options.maxReplicas ?? 10;

    return `# Terraform module for ${name}
# Generated by Spellbook

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

variable "project_id" {
  description = "GCP Project ID"
  type        = string
}

variable "image" {
  description = "Docker image for the MCP server"
  type        = string
  default     = "${options.image}"
}

provider "google" {
  project = var.project_id
  region  = "${region}"
}

# Cloud Run Service
resource "google_cloud_run_v2_service" "${name}" {
  name     = "${name}"
  location = "${region}"
  
  template {
    scaling {
      min_instance_count = ${minReplicas}
      max_instance_count = ${maxReplicas}
    }
    
    containers {
      image = var.image
      
      ports {
        container_port = 3000
      }
      
      env {
        name  = "PORT"
        value = "3000"
      }
      
      env {
        name  = "LOG_LEVEL"
        value = "info"
      }
      
      startup_probe {
        http_get {
          path = "/ready"
          port = 3000
        }
        initial_delay_seconds = 5
        period_seconds        = 10
      }
      
      liveness_probe {
        http_get {
          path = "/health"
          port = 3000
        }
        period_seconds = 30
      }
    }
  }
  
  traffic {
    type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    percent = 100
  }
}

# Make service public
resource "google_cloud_run_service_iam_member" "${name}_public" {
  location = google_cloud_run_v2_service.${name}.location
  service  = google_cloud_run_v2_service.${name}.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}

# Outputs
output "service_url" {
  value       = google_cloud_run_v2_service.${name}.uri
  description = "Cloud Run service URL"
}
`;
}

// ============================================================================
// Generator
// ============================================================================

export function generateTerraformModule(spell: Spell, options: TerraformOptions): string {
    switch (options.provider) {
        case 'aws':
            return generateAWSModule(spell, options);
        case 'gcp':
            return generateGCPModule(spell, options);
        case 'azure':
            return `# Azure Container Apps module coming soon for ${spell.name}`;
        default:
            throw new Error(`Unknown provider: ${options.provider}`);
    }
}
